### ISSUE TITLE
Deleting and rebuilding the device plugin pod will result in [Segmentation faults] in running tasks

### ISSUE THREAD

**Issue by coldzerofear** [coldzerofear/vgpu-manager#1]
### Reproduce steps
1. Submit a vGPU pod
2. Running GPU tasks in pod
3. Delete the device plugin on the corresponding node
4. Observing GPU task interrupt returning Segmentation fault (core dumped)

### Analyze the reasons
Device plugin pod reconstruction caused the init container to restart and overwrite old files on the host, which affected ongoing tasks
``` yaml
      initContainers:
        - name: install
          command: ["/bin/bash", "-c", "cp /installed/* /etc/vgpu-manager/"]
          image: coldzerofear/vgpu-manager:latest
```
